# -*- coding: utf-8 -*-
"""requirements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHaWykSN1agSuRZ-hk38MZixZrjRTaHl
"""

with open("requirements.txt","w") as f:
  f.write('streamlit\n')
  f.write("pandas\n")
  f.write("matplotlib\n")
  f.write("seaborn\n")
print('requirements.txt is created')

!pip install -r requirements.txt